# ۱. استفاده از نسخه جدیدتر پایتون (هماهنگ با جنگو ۳.۱۲ که در مسیرت بود)
# نسخه slim برای مک تو بسیار سریع‌تر و سبک‌تره
FROM python:3.12-slim

# ۲. تنظیمات محیطی
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# ۳. نصب پیش‌نیازهای سیستمی (اگر دیتابیس Postgres داری این‌ها لازم هستن)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# ۴. تعیین پوشه کاری
WORKDIR /app

# ۵. نصب پکیج‌ها (استفاده از کش داکر)
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# ۶. کپی کردن کل پروژه
COPY . /app/

# ۷. باز کردن پورت (جنگو معمولا ۸۰۰۰ است)
EXPOSE 8000

# ۸. دستور اجرا (به صورت لیست بنویس که استانداردتره)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
