# Generated by Django 4.2 on 2026-08-10 13:47

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='id_code',
            field=models.CharField(default=accounts.models.random_id_code, max_length=10, unique=True, validators=[accounts.models.validate_id_code]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(default=accounts.models.random_mobile, max_length=11, unique=True, validators=[accounts.models.validate_mobile]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='uuid_id',
            field=models.CharField(default=accounts.models.generate_short_uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
